name: Eksamensanalyse
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.12
  - notebook
  - pandas
  - matplotlib
  - seaborn
  - numpy
  - plotly
  - openpyxl

